version: "3.9"

services:

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=fundinfo
      - POSTGRES_USER=blackroom
      - POSTGRES_PASSWORD=a.b.33!?
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: inside.black.room@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 'a.b.33!?'
    ports:
      - "5050:80"

  rabbitmq:
    image: "rabbitmq:3.13.7-management-alpine"
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


volumes:
    postgres-data:
    redis-data:

